### ISSUE TITLE
Update to Motor 2.3.0

### ISSUE THREAD

**Issue by ShaneHarvey** [conda-forge/motor-feedstock#11]
Motor maintainer here, Motor 2.3.0 is the latest version: 
https://pypi.org/project/motor/2.3.0/
https://github.com/mongodb/motor/releases/tag/2.3.0

@mariusvniekerk, is there a plan to update this package? @crusaderky has been trying to update this package for a while and hasn't gotten any response. They're now asking about it in https://jira.mongodb.org/browse/MOTOR-626.

**Comment by mariusvniekerk** [comment]
okay updated this one.  Feel free to add yourself as a maintainer here

**Comment by ShaneHarvey** [comment]
Thanks!
